name: Create new realease
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: install fuse and libfuse2
      run: sudo apt install fuse libfuse2

    - name: nwjs-ffmpeg-prebuilt
      run: |
        set -x
        mkdir -p lib_extra/tmp/
        cd lib_extra/tmp/

        wget $(wget -q https://api.github.com/repos/nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt/releases/latest -O - | grep browser_download_url | grep -i linux | grep -i 64 | cut -d '"' -f 4 | head -1)
        unzip *.zip

        cd ../
        mv ./tmp/libffmpeg.so ./libffmpeg.so

    - name: WidevineCdm
      run: |
       cd lib_extra/
        mkdir tmp2/
        cd tmp2/

        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        ar x *.deb
        tar xf data.tar.xz
        cd ../
        mv tmp2/opt/google/chrome/WidevineCdm/_platform_specific/linux_x64/libwidevinecdm.so libwidevinecdm.so

        rm -R -f tmp*
        chmod a+x *.so

    - name: build
      run: |
        set -x

        ./opera_builder.sh
        ls -lah
        pwd

    # Build - Error: Resource not accessible by integration
    # Change Settings -> Actions -> General -> Workflow Permissions to allow read and write:
    # https://github.com/actions/first-interaction/issues/10#issuecomment-1506118886

    # https://github.com/marketplace/actions/upload-to-github-release
    - uses: xresloader/upload-to-github-release@main
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          file: "Opera*.AppImage; Opera*.md5"
          #delete_file: "random-name-*.txt;random-*.txt"
          release_id: ${{ steps.create_release.outputs.id }}
          #overwrite: true
          verbose: true
          #tags: true
          draft: false
