name: Create new realease
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install fuse and libfuse2
      run: sudo apt install fuse libfuse2

    - name: nwjs-ffmpeg-prebuilt
      run: |
        set -x
        mkdir -p lib_extra/tmp/
        cd lib_extra/tmp/

        wget $(wget -q https://api.github.com/repos/nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt/releases/latest -O - | grep browser_download_url | grep -i linux | grep -i 64 | cut -d '"' -f 4 | head -1)
        unzip *.zip

        pwd
        ls -lah

        cd ../
        mv ./tmp/libffmpeg.so ./libffmpeg.so

        pwd
        ls -lah

    - name: WidevineCdm
      run: |
        set -x
        cd lib_extra/
        mkdir tmp2/
        cd tmp2/

        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

        pwd
        ls -lah
 
        ar x *.deb
        tar xf data.tar.xz
        cd ../
        mv tmp2/opt/google/chrome/WidevineCdm/_platform_specific/linux_x64/libwidevinecdm.so libwidevinecdm.so

        pwd
        ls -lah

        rm -r tmp*/
        chmod +x *.so

        pwd
        ls -lah

    - name: appimagetool
      run: |
        set -x
        mkdir tmp/
        mv lib_extra/ tmp/
        cd tmp/

        wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage

        pwd
        ls -lah

    - name: Opera
      run: |
        set -x
        cd tmp/

        version_deb=$(wget -q https://deb.opera.com/opera-stable/pool/non-free/o/opera-stable/ -O - | grep deb | tail -1 | grep -o -P '(?<=.deb">).*(?=</a>)')
        wget "https://deb.opera.com/opera-stable/pool/non-free/o/opera-stable/$version_deb"

        pwd
        ls -lah

    - name: Make AppImage
      run: |
        set -x
        cd tmp/

        ar x *.deb
        tar xf data.tar.xz
        mkdir opera.AppDir/

        mv usr/lib/x86_64-linux-gnu/opera/* opera.AppDir/
        mv usr/share/applications/*.desktop opera.AppDir/

        sed -i -e '/TargetEnvironment/d' opera.AppDir/*.desktop
        mv usr/share/pixmaps/* opera.AppDir/

        tar xf control.tar.xz
        VERSION=$(cat control | grep -i version | cut -c 10-)

        cat >> opera.AppDir/AppRun << 'EOF'
        #!/bin/bash
        HERE="$(dirname "$(readlink -f "${0}")")"
        export UNION_PRELOAD="${HERE}"
        export LD_LIBRARY_PATH=/lib/:/lib64/:/lib/x86_64-linux-gnu/:/usr/lib/:"${HERE}"/lib_extra/:LD_LIBRARY_PATH
        exec "${HERE}"/opera "$@"
        EOF

        chmod +x opera.AppDir/AppRun
        mv lib_extra opera.AppDir/
        mv ../README.md opera.AppDir/

        ARCH=x86_64 ./appimagetool-x86_64.AppImage -n opera.AppDir/

        pwd
        ls -lah

        mv Opera*AppImage ../Opera-"$VERSION"-x86_64-1_JB.AppImage
        cd ../
        md5sum Opera-"$VERSION"-x86_64-1_JB.AppImage > Opera-"$VERSION"-x86_64-1_JB.AppImage.md5

    - uses: xresloader/upload-to-github-release@main
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          file: "Opera*.AppImage; Opera*.md5"
          release_id: ${{ steps.create_release.outputs.id }}
          verbose: true
          draft: false
